spring:
  datasource:
    username: param
    password: param
    url: jdbc:h2:D:/project/community
    driver-class-name: org.h2.Driver

#    schema:
#      - classpath:department.sql

qcloud:
  secretId: AKID2kpgW7JXNxOYT8Re18g7HBoBHpCKuyPa
  secretKey: 34oLdmhMmBOwIPHMCkAMKceRqzsZFTWK
  bucketName: coder-image-1253857571
  region: ap-chengdu
